### PR TITLE
Fixed practice 1

### PR DESCRIPTION
**Pull request by antonkosterev**

### CODE REVIEW

**Comment by antonkosterev** [comment]
I created a new branch and uploaded the fixed project into it with one commit. I fixed "ToBin" function

**Comment by vitalygrischenko** [comment]
This is not necessary, because it is difficult to track your changes19 мар. 2019 г. 13:16 пользователь antonkosterev <notifications@github.com> написал:I created a new branch and uploaded the fixed project into it with one commit. I fixed "ToBin" function

**Comment by antonkosterev** [comment]
I created a new brunch because I could not commit changes to "feature/practice1". 
The "feature / practice1" brunch was closed and I could not commit to it.

**Comment by antonkosterev** [comment]
Did I was to reopen "feature/practice1" for making changes ?

**Pull request closed without merging**
